server:
  port: 8080
spring:
  application:
    name: "PersonalProject"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      #uri: "mongodb://localhost:27017/pinate"
      uri: "mongodb+srv://jaras:jaras123@miprimerbase.h0qru.mongodb.net/pinate?retryWrites=true&w=majority"
